TRUTH = (
    "Apakah kamu pernah membuat hantu seseorang?",
    "Pernahkah kamu mendatangi orang tuamu melakukan 'itu'?",
    "Siapa orang terakhir yang paling kamu sukai? Kenapa?",
    "Apakah kamu pernah diskors dari sekolah?",
    "Jika Anda harus memilih antara telanjang atau pikiran Anda muncul dalam gelembung pikiran di atas kepala Anda untuk dibaca semua orang, mana yang akan Anda pilih?",
    "Apa satu hal yang kamu takut kehilangan?",
    "Apakah kamu menyukai seseorang untuk saat ini?",
    "Satu hal tentang sahabatmu yang membuatmu cemburu?",
    "Apakah kamu akan mengkhianati pacarmu untuk pria kaya?",
    "Apa ketakutan terbesarmu?",
    "Kapan terakhir kali kamu berbohong kepada orang tuamu dan mengapa?",
    "Jelaskan pasangan ideal Anda.",
    "Apa hal paling menakutkan yang pernah kamu lakukan?",
    "Apakah kamu pernah mengupil dan memakannya?",
    "Kapan terakhir kali kamu berbohong kepada orang tuamu dan mengapa?",
    "Apakah Anda pernah berbohong tentang usia Anda untuk berpartisipasi dalam kontes?",
    "Apakah kamu pernah ketahuan sedang memeriksa seseorang?",
)

DARE = (
    "Kirimkan foto paling memalukan di ponsel Anda",
    "Sebutkan lima orang terakhir yang Anda kirimi SMS dan apa isi pesannya",
    "Screenshot seluruh DM dari akun Instagram Anda",
    "Makan bawang putih mentah",
    "Lakukan 100 Spam Pada Gebetan atau Pacar",
    "Simpan tiga es batu di mulutmu sampai meleleh",
    "Katakan sesuatu yang kotor kepada orang di sebelah kirimu. Kamu punya teman!",
    "Berikan pijatan kaki pada orang di sebelah kanan Anda",
    "Masukkan 10 cairan berbeda yang tersedia ke dalam cangkir dan minumlah",
    "Katakan kata pertama yang muncul di pikiranmu",
    "Berikan video sun kepada seseorang pilihan Anda",
    "Lepaskan empat potong pakaian",
    "Suka 15 posting pertama di umpan berita Instagram Anda",
    "Makan sesendok Garam",
    "Pejamkan matamu sampai kamu tertidur",
    "Kirim sebuah chat ke orang terakhir di buku telepon Anda",
    "Pamerkan wajah orgasme Anda",
    "Makan pisang dengan menggoda",
    "Kosongkan dompet/dompet Anda dan tunjukkan kepada semua orang apa yang ada di dalamnya",
    "Lakukan fose seksi terbaikmu, lalu kirim ke lawan bermain",
    "Berpura-puralah menjadi orang di sebelah kananmu selama 10 menit",
    "Makan snack tanpa menggunakan tangan",
    "Katakan dua hal jujur ​​tentang semua orang dalam grup",
    "Kirim Foto Jelek Anda",
    "Cobalah membuat grup tertawa secepat mungkin",
    "Cobalah untuk memasukkan seluruh kepalan tanganmu ke dalam mulutmu",
    "Ceritakan kepada semua orang kisah memalukan tentang diri Anda",
    "Coba jilat sikumu",
    "Posting selfie tertua di ponsel Anda di Instagram Stories",
    "Ceritakan kisah paling menyedihkan yang kamu tahu",
    "telpon selama dua menit",
    "Menari tanpa musik selama dua menit",
    "peluk tiang lalu foto kan",
    "Biarkan orang lain menggelitikmu dan mencoba untuk tidak tertawa",
    "Masukkan makanan ringan ke dalam mulut Anda sekaligus sebanyak yang Anda bisa",
    "Kirim selfie terbaru Anda.",
    "Kirim selfiemu yang paling jelek.",
    "Kirim tangkapan layar riwayat pencarian facebook Anda",
    "Kirim tangkapan layar galeri Anda.",
    "Kirim tangkapan layar kotak masuk messenger Anda",
    "Ceritakan sesuatu yang sangat intim.",
    "Kirim tangkapan layar kotak masuk twitter Anda",
    "Kirim tangkapan layar layar beranda Anda.",
    "Kirim cover lagu favoritmu.",
    "Lakukan lelucon lirik pada seseorang dan kirimkan buktinya.",
    "Akui gebetanmu saat ini. ❤️",
    "Ungkapkan siapa cinta sejatimu.",
    "Kirim tangkapan layar galeri Anda.",
    "Jadikan foto gebetanmu sebagai foto profil anda.",
    "beri lawan bermain pantun romantis.",
)
